[project]
name = "animatagcompleter"
description = """
The extension is designed for Anima and offers simultaneous searching and tagcomplete across multiple tag sources:
• Danbooru
• Gelbooru
• Safebooru
• E621
• ThetaCursed's Artist List
Tags from all sources are organized into standard categories.

See the README in the repository for details.
"""
version = "1.1.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/Lariany-Yana/AnimaTagCompleter"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "larianyana"
DisplayName = "AnimaTagCompleter"
Icon = "https://files.catbox.moe/298rb1.webp"
Banner = "https://files.catbox.moe/405z4n.webp"
