[project]
name = "animatagcompleter"
description = "Tag completer for Anima"
version = "1.0.6"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/Lariany-Yana/AnimaTagCompleter"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "larianyana"
DisplayName = "AnimaTagCompleter"
Icon = "https://files.catbox.moe/298rb1.webp"
Banner = "https://files.catbox.moe/405z4n.webp"
